"""empty message

Revision ID: 6d4246c5cca8
Revises: 54c42a375db4
Create Date: 2023-06-03 23:36:33.428143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4246c5cca8'
down_revision = '54c42a375db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tarea', schema=None) as batch_op:
        batch_op.drop_constraint('Tarea_autor_fkey', type_='foreignkey')
        batch_op.drop_column('autor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tarea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autor', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('Tarea_autor_fkey', 'Usuario', ['autor'], ['id'])

    # ### end Alembic commands ###
